name: "Semantic Version Action (SVA)"
description: "Semantic version without any version file"

inputs:
  script:
    description: "Script to run"
    required: true
    default: "health_check"

runs:
  using: "composite"
  steps:
    - name: Init SVA
      shell: bash
      run: |
        cd ${{ github.action_path }}
        source index.sh
        health_check

    - name: Run user script
      shell: bash
      run: |
        cd ${{ github.action_path }}
        source index.sh
        cd ${{ github.workspace }}
        config_github_token 
        ${{ inputs.script }}
