name: "Semantic Version Action (SVA)"
description: "Semantic version without any version file"

inputs:
  script:
    description: "Script to run"
    required: true
    default: "health_check"

runs:
  using: "composite"
  steps:
    - name: Init SVA
      shell: bash
      run: |
        ACTION_PATH=${{ github.action_path }}
        ACTION_PATH="${ACTION_PATH//\\/\/}"
        WORKSPACE_PATH=${{ github.workspace }}
        WORKSPACE_PATH="${WORKSPACE_PATH//\\/\/}"
        cd $ACTION_PATH
        source index.sh
        cd $WORKSPACE_PATH
        health_check

    - name: Run user script
      shell: bash
      run: |
        ACTION_PATH=${{ github.action_path }}
        ACTION_PATH="${ACTION_PATH//\\/\/}"
        WORKSPACE_PATH=${{ github.workspace }}
        WORKSPACE_PATH="${WORKSPACE_PATH//\\/\/}"
        cd $ACTION_PATH
        source index.sh
        cd $WORKSPACE_PATH
        config_github_token 
        ${{ inputs.script }}
