name: Debug ubuntu

on:
  workflow_dispatch:
    inputs:
      BUILD_ENVIRONMENT_NAME:
        description: "Environment"
        required: true
        default: "development"
        type: choice
        options:
          - development
          - staging
          - uat
          - production

env:
  GITHUB_TOKEN: ${{ secrets.PAT }}

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: SVA ubuntu check
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install script
        uses: /tuanngocptn/semantic-versioning-action@main
        with:
          script: increment
