name: Dummy Deployment

on:
  workflow_run:
    workflows: [Debug ubuntu, Debug macos]
    types:
      - completed

jobs:
  on-success:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - run: echo 'The triggering workflow passed'

      - name: Checkout
        uses: actions/checkout@v3

      - name: Hello world
        run: echo "Hello world"

      - name: Git log
        run: |
          git fetch --all --tags
          git log
          git describe --tags --abbrev=0

  on-failure:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'failure' }}
    steps:
      - run: echo 'The triggering workflow failed'
